"""schema inicial con operaciones y scrap

Revision ID: 209e766ea6ec
Revises: 
Create Date: 2026-05-02 04:56:22.269346+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '209e766ea6ec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('type', sa.Enum('TUBULADORA', 'IMPRESORA', 'FONDADORA', 'EMPACADORA', name='machine_type'), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'STOPPED', 'MAINTENANCE', 'IDLE', name='machine_status'), nullable=False),
    sa.Column('current_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_order_id'], ['production_orders.id'], ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machines_code'), 'machines', ['code'], unique=True)
    op.create_index(op.f('ix_machines_status'), 'machines', ['status'], unique=False)
    op.create_index(op.f('ix_machines_type'), 'machines', ['type'], unique=False)
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('TURNO_1', 'TURNO_2', 'TURNO_3', name='shift_name'), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('oee_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('availability', sa.Float(), nullable=False),
    sa.Column('performance', sa.Float(), nullable=False),
    sa.Column('quality', sa.Float(), nullable=False),
    sa.Column('oee_value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('machine_id', 'shift_id', 'date', name='uq_oee_machine_shift_date')
    )
    op.create_index(op.f('ix_oee_records_date'), 'oee_records', ['date'], unique=False)
    op.create_index(op.f('ix_oee_records_machine_id'), 'oee_records', ['machine_id'], unique=False)
    op.create_index(op.f('ix_oee_records_shift_id'), 'oee_records', ['shift_id'], unique=False)
    op.create_table('production_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=32), nullable=False),
    sa.Column('product_type', sa.String(length=64), nullable=False),
    sa.Column('product_description', sa.String(length=255), nullable=True),
    sa.Column('quantity_ordered', sa.Integer(), nullable=False),
    sa.Column('quantity_produced', sa.Integer(), nullable=False),
    sa.Column('scrap_total_kg', sa.Float(), nullable=False),
    sa.Column('unit_weight_kg', sa.Float(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'DELAYED', name='order_status'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='order_priority'), nullable=False),
    sa.Column('planned_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('planned_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_orders_machine_id'), 'production_orders', ['machine_id'], unique=False)
    op.create_index(op.f('ix_production_orders_order_number'), 'production_orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_production_orders_product_type'), 'production_orders', ['product_type'], unique=False)
    op.create_index(op.f('ix_production_orders_status'), 'production_orders', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('OPERATOR', 'SUPERVISOR', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('etl_loads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.Enum('PRODUCTION_ORDERS', 'CONFIRMATIONS', 'MATERIALS', 'SHIPMENTS', name='etl_load_kind'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'PARTIAL', 'FAILED', name='etl_load_status'), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('rows_total', sa.Integer(), nullable=False),
    sa.Column('rows_inserted', sa.Integer(), nullable=False),
    sa.Column('rows_updated', sa.Integer(), nullable=False),
    sa.Column('rows_skipped', sa.Integer(), nullable=False),
    sa.Column('rows_failed', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('error_log', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etl_loads_kind'), 'etl_loads', ['kind'], unique=False)
    op.create_index(op.f('ix_etl_loads_status'), 'etl_loads', ['status'], unique=False)
    op.create_index(op.f('ix_etl_loads_uploaded_at'), 'etl_loads', ['uploaded_at'], unique=False)
    op.create_index(op.f('ix_etl_loads_uploaded_by_id'), 'etl_loads', ['uploaded_by_id'], unique=False)
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('material_type', sa.String(length=64), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('quantity_planned', sa.Float(), nullable=False),
    sa.Column('quantity_used', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['production_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_order_id'), 'materials', ['order_id'], unique=False)
    op.create_table('ml_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('delay_probability', sa.Float(), nullable=False),
    sa.Column('predicted_delay_hours', sa.Float(), nullable=False),
    sa.Column('features_json', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['production_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_predictions_created_at'), 'ml_predictions', ['created_at'], unique=False)
    op.create_index(op.f('ix_ml_predictions_order_id'), 'ml_predictions', ['order_id'], unique=False)
    op.create_table('order_operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'READY', 'IN_PROGRESS', 'COMPLETED', name='operation_status'), nullable=False),
    sa.Column('quantity_in', sa.Integer(), nullable=False),
    sa.Column('quantity_out', sa.Integer(), nullable=False),
    sa.Column('scrap_kg', sa.Float(), nullable=False),
    sa.Column('scrap_reason', sa.Enum('QUALITY_DEFECT', 'SETUP_LOSS', 'MATERIAL_BREAK', 'OTHER', name='scrap_reason'), nullable=True),
    sa.Column('planned_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('planned_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('shift', sa.Enum('TURNO_1', 'TURNO_2', 'TURNO_3', name='shift_name'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['production_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'sequence', name='uq_op_order_sequence')
    )
    op.create_index(op.f('ix_order_operations_machine_id'), 'order_operations', ['machine_id'], unique=False)
    op.create_index(op.f('ix_order_operations_order_id'), 'order_operations', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_operations_sequence'), 'order_operations', ['sequence'], unique=False)
    op.create_index(op.f('ix_order_operations_status'), 'order_operations', ['status'], unique=False)
    op.create_table('quality_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('total_produced', sa.Integer(), nullable=False),
    sa.Column('good_units', sa.Integer(), nullable=False),
    sa.Column('defective_units', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['production_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_records_order_id'), 'quality_records', ['order_id'], unique=False)
    op.create_table('production_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('operation_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.Enum('START', 'STOP', 'PAUSE', 'RESUME', 'FORMAT_CHANGE', 'INCIDENT', 'MAINTENANCE', 'END', 'PRODUCTION_UPDATE', name='event_type'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('scrap_kg', sa.Float(), nullable=True),
    sa.Column('scrap_reason', sa.Enum('QUALITY_DEFECT', 'SETUP_LOSS', 'MATERIAL_BREAK', 'OTHER', name='scrap_reason'), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operation_id'], ['order_operations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['production_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_events_event_type'), 'production_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_production_events_machine_id'), 'production_events', ['machine_id'], unique=False)
    op.create_index(op.f('ix_production_events_operation_id'), 'production_events', ['operation_id'], unique=False)
    op.create_index(op.f('ix_production_events_order_id'), 'production_events', ['order_id'], unique=False)
    op.create_index(op.f('ix_production_events_timestamp'), 'production_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_production_events_user_id'), 'production_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_production_events_user_id'), table_name='production_events')
    op.drop_index(op.f('ix_production_events_timestamp'), table_name='production_events')
    op.drop_index(op.f('ix_production_events_order_id'), table_name='production_events')
    op.drop_index(op.f('ix_production_events_operation_id'), table_name='production_events')
    op.drop_index(op.f('ix_production_events_machine_id'), table_name='production_events')
    op.drop_index(op.f('ix_production_events_event_type'), table_name='production_events')
    op.drop_table('production_events')
    op.drop_index(op.f('ix_quality_records_order_id'), table_name='quality_records')
    op.drop_table('quality_records')
    op.drop_index(op.f('ix_order_operations_status'), table_name='order_operations')
    op.drop_index(op.f('ix_order_operations_sequence'), table_name='order_operations')
    op.drop_index(op.f('ix_order_operations_order_id'), table_name='order_operations')
    op.drop_index(op.f('ix_order_operations_machine_id'), table_name='order_operations')
    op.drop_table('order_operations')
    op.drop_index(op.f('ix_ml_predictions_order_id'), table_name='ml_predictions')
    op.drop_index(op.f('ix_ml_predictions_created_at'), table_name='ml_predictions')
    op.drop_table('ml_predictions')
    op.drop_index(op.f('ix_materials_order_id'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_etl_loads_uploaded_by_id'), table_name='etl_loads')
    op.drop_index(op.f('ix_etl_loads_uploaded_at'), table_name='etl_loads')
    op.drop_index(op.f('ix_etl_loads_status'), table_name='etl_loads')
    op.drop_index(op.f('ix_etl_loads_kind'), table_name='etl_loads')
    op.drop_table('etl_loads')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_production_orders_status'), table_name='production_orders')
    op.drop_index(op.f('ix_production_orders_product_type'), table_name='production_orders')
    op.drop_index(op.f('ix_production_orders_order_number'), table_name='production_orders')
    op.drop_index(op.f('ix_production_orders_machine_id'), table_name='production_orders')
    op.drop_table('production_orders')
    op.drop_index(op.f('ix_oee_records_shift_id'), table_name='oee_records')
    op.drop_index(op.f('ix_oee_records_machine_id'), table_name='oee_records')
    op.drop_index(op.f('ix_oee_records_date'), table_name='oee_records')
    op.drop_table('oee_records')
    op.drop_table('shifts')
    op.drop_index(op.f('ix_machines_type'), table_name='machines')
    op.drop_index(op.f('ix_machines_status'), table_name='machines')
    op.drop_index(op.f('ix_machines_code'), table_name='machines')
    op.drop_table('machines')
    # ### end Alembic commands ###
